### ISSUE TITLE
binding automation

### ISSUE THREAD

**Issue by sonoro1234** [thenumbernine/lua-ffi-bindings#2]
Hi,

I have managed to automate luajit ffi binding generation for imgui. Main reason is for following imgui changes which are very frequent.

Here is the cimgui part
https://github.com/sonoro1234/cimgui/tree/master_auto2/cimgui/generator
Here the luajit part
https://github.com/sonoro1234/LuaJIT-ImGui/tree/master_auto/lua

may be you find it usefull
comments are welcome

victor bombi

**Comment by sonoro1234** [comment]
now
https://github.com/sonoro1234/cimgui
and
https://github.com/sonoro1234/LuaJIT-ImGui

**Comment by thenumbernine** [comment]
Thanks very much for making this, and thanks for letting me know about it.  I finally got around to switching the imgui.lua in this project over to use your generated bindings.
